### ISSUE TITLE
Possible conflict with Tech Reborn

### ISSUE THREAD

**Issue by TsWKerail** [CafeteriaGuild/Winged#12]
## Useful information to include:
 - Minecraft 1.16.5
 - Winged 1.4.1
 - In the modpack I'm using which has Winged and Tech Reborn installed the recipe for the "Empty Booster" seems way to complicated. It requires two "Superconductor Upgrades" and seven "Titanium Plates". There is no alternative recipe.

**Comment by GabrielOlvH** [comment]
All of Fabric modifies boosters recipes.
