### ISSUE TITLE
Creative Wings doesn't work

### ISSUE THREAD

**Issue by DaisukeVN** [CafeteriaGuild/Winged#22]
Attached Creative Wings doesn't give you the skill to fly like Creative.

INFO: I take the creative Wings from Creative Mode.

**Comment by adriantodt** [comment]
This issue lacks a bunch of information.

What Minecraft version are you using?
What other mods do you have on your modpack?
Did any errors or warnings appeared on Minecraft's console log on startup or when trying to place the wings?
Can you give steps on how to reproduce this?

Also, AFAIK there's no difference between a crafted Creative Flight wing and a creative-tab Creative Flight wing. Both are literally the same item, down to the NBT data. (Thanks Steven for the lazy implementation)

**Comment by DaisukeVN** [comment]
**What Minecraft version are you using?**
1.16.5 - Newest Release Version of Fabric Server

**What other mods do you have on your modpack?**
http://game.mineasia.de/downloads/mineasia-alpha/MineAsia-Alpha.xml

**Did any errors or warnings appeared on Minecraft's console log on startup or when trying to place the wings?**
Nope

**Can you give steps on how to reproduce this?**
Take the Wings with (Creative) name from Creative-Inventory.
Put the Wings on with Rightclick
Change to Survival
Try to fly like Gamemode Creative but doesn't work.

**Comment by adriantodt** [comment]
> **Can you give steps on how to reproduce this?**
> Take the Wings with (Creative) name from Creative-Inventory.
> Put the Wings on with Rightclick
> Change to Survival
> Try to fly like Gamemode Creative but doesn't work.

Could not reproduce with latest Winged version.

Please, update Winged both on client and server and try again.

If it persists, it is most likely a mod incompatibility between some mod and PlayerAbilityLib. Anyways, this issue is out of Winged's scope since we don't directly handle with creative flight. (PlayerAbilityLib does that for us)
