### ISSUE TITLE
finland elytra

### ISSUE THREAD

**Issue by devomaa** [CafeteriaGuild/Winged#23]
yes

**Comment by adriantodt** [comment]
Not an issue, closing.
---

No issue against Finland (or any country, really), but all the wings were made by the community and not by me.

**All wings were used with permission from their creators**, and I'm not just gonna search a wing from Google Images and use it.
Copyright exists, after all, and issue #15 shows one example of people misrepresenting their ownership of something.

---

If you want a Finland wing, you can post your own wing submission as an issue on GitHub!
You must either own the elytra texture, or post a texture of an artist that allows the texture's usage in our mod.

We (the Cafeteria Team) may deny submissions which do not meet the mod's standards.
