### ISSUE TITLE
[Suggestion] Command to remove wings from player

### ISSUE THREAD

**Issue by jpwanabe** [CafeteriaGuild/Winged#27]
After a recent update, a few players got access to the creative wings on a server where they were supposed to be disabled due to the crafting recipe changing. The error was fixed last update, but now I need a way to remove the wings from the player or at least see if they removed them like they were requested to.

**Comment by adriantodt** [comment]
This already exists. Closing.

**Comment by jpwanabe** [comment]
Can I ask what the command is then. I could not find it and when I asked around I did not get an answer.

**Comment by adriantodt** [comment]
The command is `/winged`.

To remove a player's wing, you can use `/winged player <player_name> clear`
