### ISSUE TITLE
USA wing and creative USA wing give the wrong core when removed.

### ISSUE THREAD

**Issue by jpwanabe** [CafeteriaGuild/Winged#28]
The 2 USA wings, when removed with the dagger, give the opposite core of what you would expect.

The standard wing gives a heart of the sky

The creative one gives a core of zephyr

A player on my server said there was another set that had this same interaction but could not remember off hand what set it was.

This is how he said he got it.
![Discord_NdksamIhIH](https://user-images.githubusercontent.com/30207571/121252342-df6b1d80-c875-11eb-904d-4e323c777886.png)

**Comment by adriantodt** [comment]
Okay, this is actually a bug. 🤦🏻 Facepalm moment for sure.

Should be an easy fix, I hope. Expect a fix soon.

(Developer Notes: Error is at RemovalKnifeItem.getCoreItem function... 🤦🏻)

**Comment by NotJustAnna** [comment]
Should be fixed on latest version. Please tell me if this doesn't fixes it.
