### ISSUE TITLE
Hearts of the Sky can create ghost images of itself when shift-right-clicked in inventory

### ISSUE THREAD

**Issue by James103** [CafeteriaGuild/Winged#6]
When using the modpack All of Fabric 1.5.3 (Winged Mod 1.16-1.2 for MC 1.16), when you shift-click the Heart of the Sky while you are flying with it, the item can sometimes create ghost images of itself taking up extra inventory slots. These ghost images only exist on the client, while the server interprets them as free slots.

To reproduce:
1. Obtain a Heart of the Sky.
2. Enchant it with Mending (optional).
3. Start creative flight with it.
4. Shift right click the item in your inventory.
5. There is a chance that the item may create ghost images of itself.

In the following image, the six Hearts of the Sky are actually one and the same. Clicking on one that isn't the real one will make the other fake copies disappear.
![image](https://user-images.githubusercontent.com/37945304/91212892-77788b80-e6d6-11ea-9298-33d26f125088.png)

**Comment by GabrielOlvH** [comment]
Shouldn't happen anymore as the Heart of the Sky doesn't grant creative flight by itself anymore.
