### ISSUE TITLE
Possible conflict with hats mod

### ISSUE THREAD

**Issue by Monster-Zer0** [CafeteriaGuild/Winged#7]
Fabric API 0.19.0+build.398-1.16
MC 1.16.2

winged v 1.4.0
give me hats v 1.2.8

when using Give me hats and wearing wings.

you get this

https://i.imgur.com/dyPFgxs.png

reporting this here and on their issues board just in case.

**Comment by adriantodt** [comment]
I blame hats, I'm literally using the same code as vanilla

**Comment by GabrielOlvH** [comment]
Is this still an issue?

**Comment by GabrielOlvH** [comment]
I'm guessing it's safe to close this, please reopen if the issue still exists
